name : example-yaml-file


on:
  push:
    branches:
        - master
jobs:
  ci-part:
    runs-on: ubuntu-latest

    steps:
      - name: Run some bash command
      - run : echo "I'm a bash command, hello"

      - name: Show me a list of files in this repository
      - run : ls -la

      - name: Git clone repository
      - run : actions/checkout@v1

      - name: Show me a second time all of this repository
      - run : ls -la
